#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Console\Commands\CreateFileCommand;

$application = new Application();

// Register commands
$application->add(new CreateFileCommand());

// Run the application
$application->run();
